#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'FPGA_Mem_A', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'FPGA_MEM_A_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_MEM_A_COMPONENT_TYPE altera_avalon_onchip_memory2
#define FPGA_MEM_A_COMPONENT_NAME FPGA_Mem_A
#define FPGA_MEM_A_BASE 0x0
#define FPGA_MEM_A_SPAN 65536
#define FPGA_MEM_A_END 0xffff
#define FPGA_MEM_A_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define FPGA_MEM_A_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define FPGA_MEM_A_CONTENTS_INFO ""
#define FPGA_MEM_A_DUAL_PORT 1
#define FPGA_MEM_A_GUI_RAM_BLOCK_TYPE M10K
#define FPGA_MEM_A_INIT_CONTENTS_FILE soc_system_FPGA_Mem_A
#define FPGA_MEM_A_INIT_MEM_CONTENT 1
#define FPGA_MEM_A_INSTANCE_ID NONE
#define FPGA_MEM_A_NON_DEFAULT_INIT_FILE_ENABLED 0
#define FPGA_MEM_A_RAM_BLOCK_TYPE M10K
#define FPGA_MEM_A_READ_DURING_WRITE_MODE OLD_DATA
#define FPGA_MEM_A_SINGLE_CLOCK_OP 1
#define FPGA_MEM_A_SIZE_MULTIPLE 1
#define FPGA_MEM_A_SIZE_VALUE 65536
#define FPGA_MEM_A_WRITABLE 1
#define FPGA_MEM_A_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define FPGA_MEM_A_MEMORY_INFO_GENERATE_DAT_SYM 1
#define FPGA_MEM_A_MEMORY_INFO_GENERATE_HEX 1
#define FPGA_MEM_A_MEMORY_INFO_HAS_BYTE_LANE 0
#define FPGA_MEM_A_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define FPGA_MEM_A_MEMORY_INFO_MEM_INIT_DATA_WIDTH 128
#define FPGA_MEM_A_MEMORY_INFO_MEM_INIT_FILENAME soc_system_FPGA_Mem_A

/*
 * Macros for device 'Instruction_Mem', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'INSTRUCTION_MEM_'.
 * The prefix is the slave descriptor.
 */
#define INSTRUCTION_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define INSTRUCTION_MEM_COMPONENT_NAME Instruction_Mem
#define INSTRUCTION_MEM_BASE 0x0
#define INSTRUCTION_MEM_SPAN 4096
#define INSTRUCTION_MEM_END 0xfff
#define INSTRUCTION_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define INSTRUCTION_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define INSTRUCTION_MEM_CONTENTS_INFO ""
#define INSTRUCTION_MEM_DUAL_PORT 1
#define INSTRUCTION_MEM_GUI_RAM_BLOCK_TYPE M10K
#define INSTRUCTION_MEM_INIT_CONTENTS_FILE soc_system_Instruction_Mem
#define INSTRUCTION_MEM_INIT_MEM_CONTENT 1
#define INSTRUCTION_MEM_INSTANCE_ID NONE
#define INSTRUCTION_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define INSTRUCTION_MEM_RAM_BLOCK_TYPE M10K
#define INSTRUCTION_MEM_READ_DURING_WRITE_MODE OLD_DATA
#define INSTRUCTION_MEM_SINGLE_CLOCK_OP 1
#define INSTRUCTION_MEM_SIZE_MULTIPLE 1
#define INSTRUCTION_MEM_SIZE_VALUE 4096
#define INSTRUCTION_MEM_WRITABLE 1
#define INSTRUCTION_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define INSTRUCTION_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define INSTRUCTION_MEM_MEMORY_INFO_GENERATE_HEX 1
#define INSTRUCTION_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define INSTRUCTION_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define INSTRUCTION_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define INSTRUCTION_MEM_MEMORY_INFO_MEM_INIT_FILENAME soc_system_Instruction_Mem

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x3000
#define LED_PIO_SPAN 16
#define LED_PIO_END 0x300f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 10
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 50000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 0

/*
 * Macros for device 'FPGA_Mem_B', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'FPGA_MEM_B_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_MEM_B_COMPONENT_TYPE altera_avalon_onchip_memory2
#define FPGA_MEM_B_COMPONENT_NAME FPGA_Mem_B
#define FPGA_MEM_B_BASE 0x10000
#define FPGA_MEM_B_SPAN 65536
#define FPGA_MEM_B_END 0x1ffff
#define FPGA_MEM_B_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define FPGA_MEM_B_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define FPGA_MEM_B_CONTENTS_INFO ""
#define FPGA_MEM_B_DUAL_PORT 1
#define FPGA_MEM_B_GUI_RAM_BLOCK_TYPE M10K
#define FPGA_MEM_B_INIT_CONTENTS_FILE soc_system_FPGA_Mem_B
#define FPGA_MEM_B_INIT_MEM_CONTENT 1
#define FPGA_MEM_B_INSTANCE_ID NONE
#define FPGA_MEM_B_NON_DEFAULT_INIT_FILE_ENABLED 0
#define FPGA_MEM_B_RAM_BLOCK_TYPE M10K
#define FPGA_MEM_B_READ_DURING_WRITE_MODE OLD_DATA
#define FPGA_MEM_B_SINGLE_CLOCK_OP 1
#define FPGA_MEM_B_SIZE_MULTIPLE 1
#define FPGA_MEM_B_SIZE_VALUE 65536
#define FPGA_MEM_B_WRITABLE 1
#define FPGA_MEM_B_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define FPGA_MEM_B_MEMORY_INFO_GENERATE_DAT_SYM 1
#define FPGA_MEM_B_MEMORY_INFO_GENERATE_HEX 1
#define FPGA_MEM_B_MEMORY_INFO_HAS_BYTE_LANE 0
#define FPGA_MEM_B_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define FPGA_MEM_B_MEMORY_INFO_MEM_INIT_DATA_WIDTH 128
#define FPGA_MEM_B_MEMORY_INFO_MEM_INIT_FILENAME soc_system_FPGA_Mem_B

/*
 * Macros for device 'FPGA_Mem_C', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'FPGA_MEM_C_'.
 * The prefix is the slave descriptor.
 */
#define FPGA_MEM_C_COMPONENT_TYPE altera_avalon_onchip_memory2
#define FPGA_MEM_C_COMPONENT_NAME FPGA_Mem_C
#define FPGA_MEM_C_BASE 0x20000
#define FPGA_MEM_C_SPAN 65536
#define FPGA_MEM_C_END 0x2ffff
#define FPGA_MEM_C_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define FPGA_MEM_C_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define FPGA_MEM_C_CONTENTS_INFO ""
#define FPGA_MEM_C_DUAL_PORT 1
#define FPGA_MEM_C_GUI_RAM_BLOCK_TYPE M10K
#define FPGA_MEM_C_INIT_CONTENTS_FILE soc_system_FPGA_Mem_C
#define FPGA_MEM_C_INIT_MEM_CONTENT 1
#define FPGA_MEM_C_INSTANCE_ID NONE
#define FPGA_MEM_C_NON_DEFAULT_INIT_FILE_ENABLED 0
#define FPGA_MEM_C_RAM_BLOCK_TYPE M10K
#define FPGA_MEM_C_READ_DURING_WRITE_MODE OLD_DATA
#define FPGA_MEM_C_SINGLE_CLOCK_OP 1
#define FPGA_MEM_C_SIZE_MULTIPLE 1
#define FPGA_MEM_C_SIZE_VALUE 65536
#define FPGA_MEM_C_WRITABLE 1
#define FPGA_MEM_C_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define FPGA_MEM_C_MEMORY_INFO_GENERATE_DAT_SYM 1
#define FPGA_MEM_C_MEMORY_INFO_GENERATE_HEX 1
#define FPGA_MEM_C_MEMORY_INFO_HAS_BYTE_LANE 0
#define FPGA_MEM_C_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define FPGA_MEM_C_MEMORY_INFO_MEM_INIT_DATA_WIDTH 128
#define FPGA_MEM_C_MEMORY_INFO_MEM_INIT_FILENAME soc_system_FPGA_Mem_C


#endif /* _ALTERA_HPS_0_H_ */
